#!/bin/bash
TEMPLATES=("main.yaml" "apig-data-stream.yaml")
for i in "${TEMPLATES[@]}"; do aws cloudformation validate-template --template-body file://"$i"; done

BUCKET=us-east-1-pipes-cf-artifacts
STACKNAME=tarasowski-pipes-dev-machine
echo "Starting deployment from local machine"
rm -rf build && mkdir build
aws cloudformation package --template-file main.yaml --output-template-file build/output.yaml --s3-bucket $BUCKET --region us-east-1
aws cloudformation deploy --template-file build/output.yaml --stack-name $STACKNAME --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --region us-east-1
